# Generated by Django 4.0.6 on 2022-07-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hermanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fechaDeNacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('ocupacion', models.CharField(max_length=30)),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fechaDeNacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('ocupacion', models.CharField(max_length=30)),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
            ],
        ),
    ]
