# Generated by Django 4.0.6 on 2022-07-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='padre',
            new_name='padres',
        ),
    ]
