# Generated by Django 4.0.6 on 2022-07-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0002_rename_padre_padres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hermanos',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='hermanos',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='padres',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='padres',
            name='peso',
        ),
    ]
